#!/usr/bin/env bash
# Bundle the notebook widget's JavaScript.
#
# The renderer is the panel's -- `vscode-extension/media/scene3d.mjs` -- so the
# two views cannot drift, and three.js is the copy the extension already
# depends on. Run `npm install` in `vscode-extension/` first.
#
# Two passes, because the widget loads the renderer as *text*: one module
# instance per view, made from a blob URL, which is what lets two cells hold
# two scenes. See the note at the top of `magpylib_studio/static/widget.mjs`.
#
#   1. scene3d.mjs + three           ->  build/renderer.txt   (not tracked)
#   2. widget.mjs, legend.mjs + that  ->  magpylib_studio/static/widget.js
#
# The product is committed: a wheel is built by hatchling alone, and nobody
# installing magpylib-studio should need node.
set -euo pipefail

ESBUILD=esbuild@0.25.10
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$here"

if [ ! -d vscode-extension/node_modules/three ]; then
  echo "three.js is missing: run 'npm install' in vscode-extension/ first." >&2
  exit 1
fi

version="$(node -p "require('./vscode-extension/node_modules/three/package.json').version")"
mkdir -p build

# What the product was built from, stamped into it. The bundle is committed,
# so the failure to guard against is an edit to `scene3d.mjs` -- made for the
# panel, which loads that file directly -- leaving the widget on the renderer
# it had. `harness/check-widget.js` recomputes this and says so.
#
# Every module of the widget's own by glob, not by name: a list is what a new
# module gets left out of, and then the hash vouches for a bundle it does not
# cover. Hashed in sorted order, which is the order the check takes them in.
sources=(magpylib_studio/static/*.mjs vscode-extension/media/scene3d.mjs)
digest="$(node -e '
const fs = require("fs");
const hash = require("crypto").createHash("sha256");
for (const file of process.argv.slice(1).sort()) hash.update(fs.readFileSync(file));
console.log(hash.digest("hex"));
' "${sources[@]}")"

npx --yes "$ESBUILD" vscode-extension/media/scene3d.mjs \
  --bundle --format=esm --minify --target=es2022 \
  --outfile=build/renderer.txt

npx --yes "$ESBUILD" magpylib_studio/static/widget.mjs \
  --bundle --format=esm --minify --target=es2022 \
  --loader:.txt=text \
  --banner:js="// Generated by tools/build-widget.sh -- do not edit.
// Sources: magpylib_studio/static/*.mjs, vscode-extension/media/scene3d.mjs,
//          three.js $version
// sources-sha256: $digest" \
  --outfile=magpylib_studio/static/widget.js

echo "built magpylib_studio/static/widget.js ($(wc -c < magpylib_studio/static/widget.js) bytes)"
